package j2d.color;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import j2d.Utils;

import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import java.awt.*;

public class ColorPanelController {
    private JPanel rootPanel;
    private JSlider slider1;
    private JSlider slider2;
    private JSlider slider3;
    private ColorPanel colorPanel;

    public ColorPanelController() {
        slider1.addChangeListener(changeEvent -> {
            colorPanel.red = slider1.getValue();
            colorPanel.repaint();
        });
        slider2.addChangeListener(changeEvent -> {
            colorPanel.green = slider2.getValue();
            colorPanel.repaint();
        });
        slider3.addChangeListener(changeEvent -> {
            colorPanel.blue = slider3.getValue();
            colorPanel.repaint();
        });
    }

    public static void main(String[] args) {
        Utils.runFrame(() -> new ColorPanelController().$$$getRootComponent$$$());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        rootPanel.add(panel1, BorderLayout.EAST);
        slider1 = new JSlider();
        slider1.setMaximum(255);
        slider1.setOrientation(1);
        panel1.add(slider1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        slider2 = new JSlider();
        slider2.setMaximum(255);
        slider2.setOrientation(1);
        slider2.setValue(50);
        panel1.add(slider2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        slider3 = new JSlider();
        slider3.setMaximum(255);
        slider3.setOrientation(1);
        panel1.add(slider3, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        colorPanel = new ColorPanel();
        colorPanel.setLayout(new BorderLayout(0, 0));
        rootPanel.add(colorPanel, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

}
